name: Categories
form: $/niainteractive/niacalendar/models/category/fields.yaml
modelClass: NiaInteractive\NiaCalendar\Models\Category
defaultRedirect: niainteractive/niacalendar/categories
create:
    redirect: 'niainteractive/niacalendar/categories/update/:id'
    redirectClose: niainteractive/niacalendar/categories
update:
    redirect: niainteractive/niacalendar/categories
    redirectClose: niainteractive/niacalendar/categories
