plugin:
    name: 'niainteractive.niacalendar::lang.plugin.name'
    description: 'niainteractive.niacalendar::lang.plugin.description'
    author: NiaInteractive
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-nia-niacalendars:
        label: Nia Calendar
        url: niainteractive/niacalendar/niacalendars
        icon: icon-certificate
        sideMenu:
            side-menu-nia-niacalendars:
                label: Nia Calendar
                url: niainteractive/niacalendar/niacalendars
                icon: icon-certificate
            side-menu-categories:
                label: Categories
                url: niainteractive/niacalendar/categories
                icon: icon-sitemap
