list: $/niainteractive/niacalendar/models/niacalendar/columns.yaml
modelClass: NiaInteractive\NiaCalendar\Models\NiaCalendar
title: NiaCalendars
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'niainteractive/niacalendar/niacalendars/update/:id'
